services:
  node-butler-frontend:
    build: "${DOCKER_PATH}"
    # volumes:
    #   - .:/app/
    ports:
      - "3002:3000"
  node-butler-frontend-1:
    build: "${DOCKER_PATH}"
    # volumes:
    #   - .:/app/
    ports:
      - "3003:3000"
  node-butler-frontend-2:
    build: "${DOCKER_PATH}"
    # volumes:
    #   - .:/app/
    ports:
      - "3004:3000"
